web/apps/client/urls.py
from django.urls import path
from apps.client.views import ProductTemplateViewSet, render_fitting, UserTemplateViewSet

app_name = "client"

urlpatterns = [
    path("", ProductTemplateViewSet.as_view(), name="home"),
    path("fitting/", render_fitting, name="fitting"),
    path("browse/", UserTemplateViewSet.as_view(), name="browse"),
]

web/config/urls.py
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from apps.core.types import APIUrlPatternsType, UrlCompositePatternsType, UrlPatternsType

api_urlpatterns: UrlPatternsType = [
    # path('admin/', admin.site.urls),
    path('', include('apps.client.urls')),
    path('api/users/', include('apps.users.urls.users')),
    path('api/products/', include('apps.products.urls')),
    path('accounts/', include('apps.users.urls.accounts')),
    path('alarms/', include('apps.alarms.urls')),
]

swagger_urlpatterns: APIUrlPatternsType = [
    # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns: UrlCompositePatternsType = api_urlpatterns + swagger_urlpatterns

web/templates/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Suitcase</title>

    <!-- 3rd Party Modeules -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'django_eventstream/eventsource.min.js' %}"></script>
    <script src="{% static 'django_eventstream/reconnecting-eventsource.js' %}"></script>
    <script type="module">
        import("/static/js/index.js").then(module => {
            module.start("{{user.username}}");
        });
    </script>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}
</head>
<body class="bg-my-beige-500 flex justify-center">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
    <div class="screen-frame flex flex-col w-screen max-w-screen-lg">
        {% if is_logged_in %}
            {% include "navbar.html" %}
        {% endif %}
        <div class="push-notification-container fixed right-0 z-30">

        </div>
        {% block content %}
        {% endblock %}
    </div>
    {% block javascripts %}
    {% endblock %}
    <script>
        const closePushNotification = (target) => {
            const pushNoti = target.closest('.push-notification');
            console.log(pushNoti)
            pushNoti.classList.add('hidden');
        }
    </script>
</body>
</html>

web/templates/navbar.html
{% load compress %}
{% load static %}
<nav class="bg-gray-50 dark:bg-gray-700 w-full">
    <div class="min-w-screen-md max-w-screen-lg px-4 py-3 mx-auto flex justify-between">
        <div class="flex items-center">
            <ul class="flex flex-row font-medium mt-0 mr-6 space-x-8 text-sm">
                <li>
                    <a href="{% url 'client:home' %}" class="nav-anchor text-gray-900 dark:text-white hover:underline" aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{% url 'client:fitting' %}" class="nav-anchor text-gray-900 dark:text-white hover:underline">Fitting</a>
                </li>
                <li>
                    <a href="{% url 'client:browse' %}" class="nav-anchor text-gray-900 dark:text-white hover:underline">Browse</a>
                </li>
            </ul>
        </div>
        {% if is_logged_in %}
        <div class="flex items-center md:order-2">
            <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
            <span class="sr-only">Open user menu</span>
            <img class="w-8 h-8 rounded-full bg-white" src="/static/icons/{{rand_svg_num}}.svg" alt="random clothes">
            </button>
            <!-- Dropdown menu -->
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
            <div class="px-4 py-3">
                <span class="block text-sm text-gray-900 dark:text-white">{{user.username}}</span>
                <span class="block text-sm  text-gray-500 truncate dark:text-gray-400"><a class="cursor-pointer" href="{{user.user_url}}">{{user.user_url}}</a></span>
            </div>
            <div class="px-4 py-3">
                <span class="block text-sm text-gray-900 dark:text-white">
                    <button
                        type="button"
                        data-modal-target="edit-url-modal"
                        data-modal-toggle="edit-url-modal"
                    >Edit your link
                    </button>
                </span>
            </div>
            <ul class="py-2" aria-labelledby="user-menu-button">
                <li>
                    <a href="{% url 'accounts:logout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
                </li>
            </ul>
            </div>
        </div>
        {% endif %}
    </div>
</nav>

<!-- Edit Url Modal -->
<div id="edit-url-modal" tabindex="-1" class="hidden fixed top-0 left-0 right-0 z-50 w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-xl font-medium text-gray-900 dark:text-white">
                    Edit your link
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="edit-url-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="w-full p-5">
                <form id="edit-url-form" class="flex flex-col space-y-2">
                    {% csrf_token %}
                    <div class="relative w-full">
                        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
                                <path xmlns="http://www.w3.org/2000/svg" d="M6.92896 14.7205L6.45643 15.193C5.97241 15.677 5.31592 15.9488 4.63141 15.9488C3.94689 15.9488 3.29041 15.677 2.80638 15.193C2.32235 14.7091 2.05043 14.0527 2.05043 13.3682C2.05043 12.6838 2.32235 12.0274 2.80638 11.5435L6.44926 7.90115C6.94099 7.43196 7.59458 7.17018 8.27428 7.17018C8.95399 7.17018 9.60758 7.43196 10.0993 7.90115C10.2926 8.08784 10.5515 8.19114 10.8203 8.1888C11.0891 8.18647 11.3461 8.07868 11.5362 7.88867C11.7262 7.69865 11.834 7.4416 11.8364 7.17289C11.8387 6.90417 11.7354 6.64529 11.5487 6.452C10.6802 5.58378 9.50239 5.09603 8.27428 5.09603C7.04617 5.09603 5.86836 5.58378 4.9999 6.452L1.35702 10.0943C0.926887 10.5243 0.58566 11.0347 0.352822 11.5965C0.119985 12.1583 9.52375e-05 12.7604 5.67953e-08 13.3685C-0.000192169 14.5967 0.487574 15.7746 1.356 16.6432C2.22442 17.5117 3.40236 17.9998 4.63068 18C5.85901 18.0002 7.0371 17.5125 7.90579 16.6442L8.37832 16.1728C8.57065 15.9806 8.67876 15.7199 8.67886 15.448C8.67895 15.1762 8.57103 14.9154 8.37883 14.7231C8.18664 14.5308 7.92591 14.4227 7.654 14.4226C7.3821 14.4225 7.12129 14.5304 6.92896 14.7226V14.7205Z" fill="#2F2F38"/>
                                <path xmlns="http://www.w3.org/2000/svg" d="M16.6471 1.35334C15.778 0.486688 14.6006 0 13.3732 0C12.1457 0 10.9684 0.486688 10.0993 1.35334L9.37258 2.07894C9.27097 2.17258 9.18935 2.28578 9.13262 2.41176C9.0759 2.53774 9.04523 2.67389 9.04246 2.81202C9.0397 2.95015 9.0649 3.08742 9.11654 3.21556C9.16819 3.34371 9.24521 3.46009 9.34299 3.55772C9.44076 3.65534 9.55727 3.73219 9.68551 3.78365C9.81375 3.8351 9.95107 3.8601 10.0892 3.85714C10.2274 3.85418 10.3635 3.82333 10.4894 3.76643C10.6153 3.70953 10.7284 3.62776 10.8219 3.52604L11.5487 2.79941C12.0354 2.32877 12.6876 2.06822 13.3647 2.07393C14.0418 2.07964 14.6895 2.35115 15.1682 2.82993C15.6469 3.30871 15.9183 3.95641 15.9238 4.63339C15.9293 5.31037 15.6685 5.96241 15.1977 6.44893L11.5558 10.0913C11.064 10.5602 10.4105 10.8218 9.73082 10.8218C9.05119 10.8218 8.39764 10.5602 7.90579 10.0913C7.81124 9.99338 7.69813 9.91531 7.57308 9.8616C7.44802 9.80789 7.31352 9.77961 7.17742 9.77843C7.04132 9.77725 6.90635 9.80318 6.78038 9.85471C6.65441 9.90624 6.53997 9.98234 6.44373 10.0786C6.34749 10.1748 6.27138 10.2892 6.21984 10.4152C6.1683 10.5411 6.14236 10.6761 6.14355 10.8122C6.14473 10.9482 6.17301 11.0827 6.22673 11.2078C6.28045 11.3328 6.35853 11.4459 6.45643 11.5404C7.32489 12.4086 8.50271 12.8964 9.73082 12.8964C10.9589 12.8964 12.1367 12.4086 13.0052 11.5404L16.6471 7.89808C17.5135 7.02934 18 5.85255 18 4.62571C18 3.39887 17.5135 2.22208 16.6471 1.35334Z" fill="#2F2F38"/>
                            </svg>
                        </div>
                        <input
                            name="user_url"
                            type="text"
                            id="simple-search"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Put your representative url here." required
                            value="{{user.user_url}}"
                        >
                    </div>
                </form>
            </div>
            <!-- Modal footer -->
            <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                <button
                    data-modal-hide="edit-url-modal"
                    type="submit"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                    onclick="edit_user_url()"
                >I accept</button>
                <button
                    data-modal-hide="edit-url-modal"
                    type="button"
                    class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600"
                    onclick="on_decline_btn()"
                >Decline</button>
            </div>
        </div>
    </div>
</div>

<script>
    const pathname = new URL(location.href).pathname
    const nav_anchors = Array.from(document.querySelectorAll(".nav-anchor"))
    nav_anchors.forEach((nav_anchor) => {
        const nav_text = nav_anchor.innerText.toLowerCase();
        if (`/${nav_text}/` === pathname) {
            nav_anchor.classList.add("font-bold")
        } else if (nav_text === "home" && pathname === "/") {
            nav_anchor.classList.add("font-bold")
        } else {
            nav_anchor.classList.remove("font-bold")
        }
    })

    async function update_user_url_api(method, user_id, data) {
        return axios({
            method: method,
            url: `/api/users/${user_id}/`,
            headers: {
                "Content-Type": "multipart/form-data",
                'X-CSRFToken': '{{csrf_token}}'
            },
            data: data,
        }).then((res) => {
            return res;
        }).catch(() => {
            alert("ERROR")
        });
    }
    const edit_user_url = async () => {
        const form_object = document.getElementById('edit-url-form');
        const bodyFormData = new FormData(form_object);
        if (!confirm('Are you sure you want to update?')) {
            return;
        } 
        await update_user_url_api('patch', "{{user.id}}", bodyFormData);
        location.reload();
    }

    const on_decline_btn = () => {
        const form_object = document.getElementById('edit-url-form');
        const url_input = form_object.querySelector('input[name="user_url"]');
        url_input.value = "{{user.user_url}}";
    }
</script>